Move subsetCheck to Set Interface
in-toto/in-toto-golang pull request #73
Opened 2020-08-20 19:55 UTC by shibumi

**Fixes issue #**:
https://github.com/in-toto/in-toto-golang/issues/66

**Description of pull request**:
This Requests fulfils issue #66 and moves the subsetCheck function into our Set interface.

**Please verify and check that the pull request fulfills the following
requirements**:

- [X] Tests have been added for the bug fix or new feature
- [X] Docs have been added for the bug fix or new feature

2020-08-20 19:55 UTC, shibumi commented
This PR is ready to merge

2020-08-24 23:14 UTC, shibumi commented
@lukpueh you might want to have another look :)

2020-08-25 09:41 UTC, lukpueh requested changes
Thanks for the changes! Almost there. :)

2020-08-25 09:41 UTC, lukpueh commented on in_toto/util_test.go
> +		{[]string{"sha256", "sha512"}, Set{"sha128": {}, "sha256": {}, "sha512": {}}, true},
Minor nit: I think it's a tad more readable if you use e.g. `NewSet{"sha256",  "sha512"}`, etc.

2020-08-25 09:41 UTC, lukpueh commented on in_toto/util.go
> +func (s Set) IsSubSet(subset Set) bool {
Minor performance nit: You could do a quick len check to return early (subset can't be greater than superset).

2020-08-25 09:41 UTC, lukpueh commented on in_toto/util.go
> +can be found in a Set.
Please update the docstring, also so that it is clear which one is expected to be the subset and which the superset.

2020-08-26 00:56 UTC, shibumi commented
@lukpueh all done.

2020-08-26 07:24 UTC, lukpueh approved these changes
💯

2020-08-26 07:24 UTC, merged